name: Generate K8s admin manifests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : GITHUB CONTEXT
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }} 
      run: echo "$GITHUB_CONTEXT" 

    - name: get commit message
      run: |
          echo "commitmsg=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Fabrikate defs -> k8s manifests
      run: |
        ./build.sh ./bin/
      env:
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN }}
        COMMIT_MESSAGE: ${{ env.commitmsg }}
        REPO: https://github.com/sachinkundu/k8smanifests.git
        FAB_ENVS: dev